#!/bin/bash
set -euo pipefail
pushd $(dirname "$0")/..

export PROFILE=${1:-"dev"}

# Autogenerated file. Do not edit manually.

for row in $(cat manifests/$PROFILE/deployment/manifest.json | jq -r '.contracts[] | @base64'); do
    _jq() {
        echo ${row} | base64 --decode | jq -r ${1}
    }

     name=$(_jq '.name')
     address=$(_jq '.address')

     # Convert to uppercase and replace '-' with '_'
     var_name=$(echo $name | tr '[:lower:]' '[:upper:]' | tr '-' '_' | sed 's/::/_/g')

     declare "${var_name}"=$address
done
