/* Autogenerated file. Do not edit manually. */

import { Account, BigNumberish } from 'starknet'
import { DojoProvider } from "@dojoengine/core";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export async function setupWorld(provider: DojoProvider) {
  function actions() {
    const interact = async ({ account, contract_name, call, calldata }: { account: Account, contract_name: string, call: string, calldata: BigNumberish[] }) => {

      try {
        return await provider.execute(
          account,
          contract_name,
          call,
          calldata
        );
      } catch (error) {
        console.error("Error executing interact:", error);
        throw error;
      }
    };

    return { interact };
  }
  return {
    actions: actions(),
  };
}
