kind = "DojoModel"
class_hash = "0x6363714e0e5ce09675144935223ff5390e7fefe6ee059a8d62ffc79a3e146ad"
original_class_hash = "0x6363714e0e5ce09675144935223ff5390e7fefe6ee059a8d62ffc79a3e146ad"
abi = "manifests/sepolia/base/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
qualified_path = "pixelaw::core::models::pixel::pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[members]]
name = "x"
type = "u16"
key = true

[[members]]
name = "y"
type = "u16"
key = true

[[members]]
name = "app"
type = "ContractAddress"
key = false

[[members]]
name = "color"
type = "u32"
key = false

[[members]]
name = "created_at"
type = "u64"
key = false

[[members]]
name = "updated_at"
type = "u64"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "text"
type = "felt252"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
