kind = "DojoModel"
class_hash = "0x19bf5119a6b23d3f098888ea27e5639d5b89ccf046d22e00c767cd4d3f78d9d"
original_class_hash = "0x19bf5119a6b23d3f098888ea27e5639d5b89ccf046d22e00c767cd4d3f78d9d"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_pixel_pixel.json"
name = "pixelaw::core::models::pixel::pixel"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "created_at"
type = "u64"
key = false

[[members]]
name = "updated_at"
type = "u64"
key = false

[[members]]
name = "app"
type = "ContractAddress"
key = false

[[members]]
name = "color"
type = "u32"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "text"
type = "felt252"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
