kind = "DojoModel"
class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
original_class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
abi = "manifests/dev/base/abis/models/pixelaw-Permissions-72b77307.json"
tag = "pixelaw-Permissions"
qualified_path = "pixelaw::core::models::permissions::permissions"
manifest_name = "pixelaw-Permissions-72b77307"

[[members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[members]]
name = "permission"
type = "Permission"
key = false
