kind = "DojoModel"
class_hash = "0x40bff7008f593e3fa201c4b22e5cf172217620a5605bdab71e09d9a9a9d781a"
original_class_hash = "0x40bff7008f593e3fa201c4b22e5cf172217620a5605bdab71e09d9a9a9d781a"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_registry_instruction.json"
name = "pixelaw::core::models::registry::instruction"

[[members]]
name = "system"
type = "ContractAddress"
key = true

[[members]]
name = "selector"
type = "felt252"
key = true

[[members]]
name = "instruction"
type = "felt252"
key = false
