kind = "DojoModel"
class_hash = "0x74c630be9062098affb2ac8b27955ebaa8c863319800213a34ccc02ca97fc9"
original_class_hash = "0x74c630be9062098affb2ac8b27955ebaa8c863319800213a34ccc02ca97fc9"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_registry_app.json"
name = "pixelaw::core::models::registry::app"

[[members]]
name = "system"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "manifest"
type = "felt252"
key = false

[[members]]
name = "icon"
type = "felt252"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
