kind = "DojoModel"
class_hash = "0x2fbf92676699542bb22322de6b8c9930c28a017b89f444ebdc7fb293496295d"
original_class_hash = "0x2fbf92676699542bb22322de6b8c9930c28a017b89f444ebdc7fb293496295d"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_registry_app_name.json"
name = "pixelaw::core::models::registry::app_name"

[[members]]
name = "name"
type = "felt252"
key = true

[[members]]
name = "system"
type = "ContractAddress"
key = false
