kind = "DojoModel"
class_hash = "0x29faa42389b762ddb248311c81d68095c0fec2cfd7810b31e62af19675b0afb"
original_class_hash = "0x29faa42389b762ddb248311c81d68095c0fec2cfd7810b31e62af19675b0afb"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_registry_core_actions_address.json"
name = "pixelaw::core::models::registry::core_actions_address"

[[members]]
name = "key"
type = "felt252"
key = true

[[members]]
name = "value"
type = "ContractAddress"
key = false
