kind = "DojoModel"
class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
original_class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
abi = "manifests/dev/base/abis/models/pixelaw-AppName-3b816829.json"
tag = "pixelaw-AppName"
qualified_path = "pixelaw::core::models::registry::app_name"
manifest_name = "pixelaw-AppName-3b816829"

[[members]]
name = "name"
type = "felt252"
key = true

[[members]]
name = "system"
type = "ContractAddress"
key = false
