kind = "DojoModel"
class_hash = "0x21694db3f07ef20ac056336fd80757d8883bae2a2329ca9ade1d681fe9ae883"
original_class_hash = "0x21694db3f07ef20ac056336fd80757d8883bae2a2329ca9ade1d681fe9ae883"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_registry_app_user.json"
name = "pixelaw::core::models::registry::app_user"

[[members]]
name = "system"
type = "ContractAddress"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "action"
type = "felt252"
key = false
