kind = "DojoModel"
class_hash = "0x55935fbd47fb70609ca521bbafaa69a03919f77c45bb8ad0e221af4658a9a6b"
original_class_hash = "0x55935fbd47fb70609ca521bbafaa69a03919f77c45bb8ad0e221af4658a9a6b"
abi = "manifests/dev/abis/base/models/pixelaw_core_models_permissions_permissions.json"
name = "pixelaw::core::models::permissions::permissions"

[[members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[members]]
name = "permission"
type = "Permission"
key = false
