kind = "DojoModel"
class_hash = "0xa5fff6fee52fd6a9d07e39f7039926783a2d8fc397a87617593c689124e113"
original_class_hash = "0xa5fff6fee52fd6a9d07e39f7039926783a2d8fc397a87617593c689124e113"
abi = "manifests/dev/abis/base/models/pixelaw_apps_snake_app_snake_segment.json"
name = "pixelaw::apps::snake::app::snake_segment"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "previous_id"
type = "u32"
key = false

[[members]]
name = "next_id"
type = "u32"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "pixel_original_color"
type = "u32"
key = false

[[members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false
