[world]
description = "Populated PixeLAW world"
name = "dev-pop"
seed = 'dev-pop'

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x3c4dd268780ef738920c801edc3a75b6337bc17558c74795b530c0ff502486"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x5729e109ed70ce4f33e3164505c78476e9fec57874b69467cdf0ba51636085"

[writers]
"pixelaw-App" = ["pixelaw-actions"]
"pixelaw-AppName" = ["pixelaw-actions"]
"pixelaw-AppUser" = ["pixelaw-actions"]
"pixelaw-CoreActionsAddress" = ["pixelaw-actions"]
"pixelaw-Pixel" = [
  "pixelaw-actions",
  "pixelaw-paint_actions",
  "pixelaw-snake_actions",
]
"pixelaw-QueueItem" = ["pixelaw-actions"]
"pixelaw-Snake" = ["pixelaw-actions", "pixelaw-snake_actions"]
"pixelaw-RTree" = ["pixelaw-actions"]
"pixelaw-Area" = ["pixelaw-actions"]
"pixelaw-SnakeSegment" = ["pixelaw-snake_actions"]
