kind = "DojoContract"
class_hash = "0x9e00605511c63fa1b4366de9baf304748f30682ab4d1cc12b51d93745f7ed9"
original_class_hash = "0x9e00605511c63fa1b4366de9baf304748f30682ab4d1cc12b51d93745f7ed9"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/pixelaw-actions-16928a49.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-actions"
systems = [
    "init",
    "schedule_queue",
    "process_queue",
    "alert_player",
    "remove_area",
]
manifest_name = "pixelaw-actions-16928a49"
