kind = "DojoContract"
class_hash = "0x2cebb25adf8fe48de7d7797e77f82f8eb7b090b1f354bae20c2c895d2043461"
original_class_hash = "0x2cebb25adf8fe48de7d7797e77f82f8eb7b090b1f354bae20c2c895d2043461"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/pixelaw-paint_actions-2afb94fe.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-paint_actions"
systems = [
    "init",
    "on_post_update",
    "interact",
    "put_color",
    "pixel_row",
    "fade",
]
manifest_name = "pixelaw-paint_actions-2afb94fe"
