#Webapp

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-http
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.subDomainName.pixelaw }}.{{ .Values.domainName }}`)
      kind: Rule
      middlewares:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
          port: {{ .Values.webappContainerService.port }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-https
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.subDomainName.pixelaw }}.{{ .Values.domainName }}`)
      kind: Rule
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
          port: {{ .Values.webappContainerService.port }}
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"


#Katana
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: katana-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-http
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.subDomainName.katana }}.{{ .Values.domainName }}`)
      kind: Rule
      middlewares:
        - name: katana-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-katana
          port: {{ .Values.katanaContainerService.port }}


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: katana-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-https
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.subDomainName.katana }}.{{ .Values.domainName }}`)
      kind: Rule
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-katana
          port: {{ .Values.katanaContainerService.port }}
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: katana-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"

#Torii
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-http
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.subDomainName.torii }}.{{ .Values.domainName }}`)
      kind: Rule
      middlewares:
        - name: torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-torii
          port: {{ .Values.toriiContainerService.port }}


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-https
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.subDomainName.torii }}.{{ .Values.domainName }}`)
      kind: Rule
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-torii
          port: {{ .Values.toriiContainerService.port }}
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"

#grpcTorii
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grpc-torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-http
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.subDomainName.grpcTorii }}.{{ .Values.domainName }}`)
      kind: Rule
      middlewares:
        - name: grpc-torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-grpc-torii
          port: {{ .Values.grpcToriiContainerService.port }}


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grpc-torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-https
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.subDomainName.grpcTorii }}.{{ .Values.domainName }}`)
      kind: Rule
      services:
        - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-grpc-torii
          port: {{ .Values.grpcToriiContainerService.port }}
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grpc-torii-{{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-ingress-redirect-scheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"