apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }} 
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }} 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
