/* Autogenerated file. Do not edit manually. */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Color: (() => {
      const name = "Color";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          r: RecsType.Number,
          g: RecsType.Number,
          b: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Owner: (() => {
      const name = "Owner";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          address: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Permission: (() => {
      const name = "Permission";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          caller_system: RecsType.Number,
          allowed: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Text: (() => {
      const name = "Text";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          string: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Timestamp: (() => {
      const name = "Timestamp";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          created_at: RecsType.Number,
          updated_at: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    PixelType: (() => {
      const name = "PixelType";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          name: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    NeedsAttention: (() => {
      const name = "NeedsAttention";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          value: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    CoreActionsModel: (() => {
      const name = "CoreActionsModel";
      return defineComponent(
        world,
        {
          key: RecsType.Number,
          value: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    App: (() => {
      const name = "App";
      return defineComponent(
        world,
        {
          system: RecsType.Number,
          name: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AppName: (() => {
      const name = "AppName";
      return defineComponent(
        world,
        {
          name: RecsType.Number,
          system: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
