kind = "DojoContract"
class_hash = "0x5a51ed43d3db1d5832a76b458fc676d642e39da28190cca253b686ab9a91006"
original_class_hash = "0x5a51ed43d3db1d5832a76b458fc676d642e39da28190cca253b686ab9a91006"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pixelaw_apps_paint_app_paint_actions.json"
reads = []
writes = []
computed = []
name = "pixelaw::apps::paint::app::paint_actions"
